# Pandas & NumPy


In [1]:
import pandas as pd
import numpy as np

## Multiplicando Matrizes - Qual o jeito Certo?

In [2]:
a = [1, 2, 3, 4]

In [3]:
a*3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [4]:
b = np.array([1, 2, 3, 4])

In [5]:
b * 3

array([ 3,  6,  9, 12])

Depende do contexto! NumPy faz o que é mais perto da matemática. É um comportamento similar ao do Matlab ou do R

## Mais dimensões!

In [6]:
a = [[1, 2, 3], [4,5,6], [7,8,9]]

In [7]:
print(a)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [8]:
a[0]

[1, 2, 3]

In [9]:
a[0][0]

1

In [10]:
b = np.array(a)

In [11]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
b[0]

array([1, 2, 3])

In [13]:
b[0, 0]

1

In [14]:
b[0][0]

1

### Selecionando linhas e colunas

In [15]:
b[:, 0]

array([1, 4, 7])

In [16]:
b[0, :]

array([1, 2, 3])

### Buscando Valores!

In [17]:
b[b > 2]

array([3, 4, 5, 6, 7, 8, 9])

In [19]:
b[b < 8]

array([1, 2, 3, 4, 5, 6, 7])

### Agregações

In [20]:
np.mean(b)

5.0

In [21]:
np.sum(b)

45

In [22]:
np.std(b)

2.581988897471611

In [23]:
np.var(b)

6.666666666666667

# Pandas

In [24]:
data = pd.read_csv("data/plantas.csv")

In [25]:
data

nome_cientifico  altura_cm  idade_meses
0        Planta A         45           12
1        Planta B         60           18
2        Planta C         30            8
3        Planta D         75           24
4        Planta E         55           15
5        Planta F         40           10
6        Planta G         70           22
7        Planta H         50           14
8        Planta I         65           20
9        Planta J         38            9

In [26]:
data.describe()

altura_cm  idade_meses
count  10.000000    10.000000
mean   52.800000    15.200000
std    14.778363     5.613476
min    30.000000     8.000000
25%    41.250000    10.500000
50%    52.500000    14.500000
75%    63.750000    19.500000
max    75.000000    24.000000

In [27]:
data.altura_cm > 50

0    False
1     True
2    False
3     True
4     True
5    False
6     True
7    False
8     True
9    False
Name: altura_cm, dtype: bool

In [28]:
filtro = data.altura_cm > 50

In [29]:
data[filtro]

nome_cientifico  altura_cm  idade_meses
1        Planta B         60           18
3        Planta D         75           24
4        Planta E         55           15
6        Planta G         70           22
8        Planta I         65           20

In [30]:
data[filtro].describe()

altura_cm  idade_meses
count   5.000000      5.00000
mean   65.000000     19.80000
std     7.905694      3.49285
min    55.000000     15.00000
25%    60.000000     18.00000
50%    65.000000     20.00000
75%    70.000000     22.00000
max    75.000000     24.00000

In [31]:
# Calcular a média da altura das plantas
media_altura = data["altura_cm"].mean()
print("Média da altura das plantas:", media_altura, "cm")

# Encontrar a planta mais antiga (maior idade)
planta_mais_antiga = data[data["idade_meses"] == data["idade_meses"].max()]
print("Planta mais antiga:\n", planta_mais_antiga)


Média da altura das plantas: 52.8 cm
Planta mais antiga:
   nome_cientifico  altura_cm  idade_meses
3        Planta D         75           24
